name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: |
          forge install foundry-rs/forge-std --no-commit
          forge install OpenZeppelin/openzeppelin-contracts --no-commit

      - name: Aderyn
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cyfrin/aderyn/releases/latest/download/aderyn-installer.sh | bash
          aderyn -o report.json
          count=$(cat report.json | jq '.issue_count.high')
          if [[ $count != "0" ]]; then
            cat report.json
            exit 1
          fi
